const dummyData = [
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-09-28',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-09-29',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-09-30',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-10-01',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-10-26',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:35',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:25',
		date: '2021-10-27',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-10-28',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '2',
		departureTime: '13:25',
		arrivalAirportIata: 'SVO',
		arrivaltime: '19:15',
		date: '2021-10-29',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '4',
		departureTime: '13:30',
		arrivalAirportIata: 'SVO',
		arrivaltime: '20:20',
		date: '2021-10-31',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2579,
		departureAirportIataCode: 'LHR',
		departureTerminal: '4',
		departureTime: '13:30',
		arrivalAirportIata: 'SVO',
		arrivaltime: '20:20',
		date: '2021-11-01',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
	{
		carrierIataCode: 'SU',
		flightNumber: 2583,
		departureAirportIataCode: 'LHR',
		departureTerminal: '4',
		departureTime: '17:15',
		arrivalAirportIata: 'SVO',
		arrivaltime: '00:10',
		date: '2021-11-06',
		name: 'Aeroflot Russian Airlines',
		departureAirport: {
			lat: '51.28.39N',
			long: '000.27.41W',
			port_name: 'London Heathrow Apt',
			city_name: 'London',
		},
		arrivalAirport: {
			lat: '55.58.22N',
			long: '037.24.53E',
			port_name: 'Moscow Sheremetyevo International Apt',
			city_name: 'Moscow',
		},
	},
];
module.exports = dummyData;
